<a href="https://colab.research.google.com/github/rashmishankar08/rashmishankar08/blob/master/R6_InternalLab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [116]:
from google.colab import drive
drive.mount('/content/gdrive')
# in case issues with mounting drive

Mounted at /content/gdrive


# The Iris Dataset
The data set consists of 50 samples from each of three species of Iris (Iris setosa, Iris virginica and Iris versicolor). Four features were measured from each sample: the length and the width of the sepals and petals, in centimeters.

The dataset contains a set of 150 records under five attributes - petal length, petal width, sepal length, sepal width and species.

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [82]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [83]:
import tensorflow as tf
print(tf.__version__)

2.4.0


### Set random seed

In [84]:
tf.random.set_seed(42)

## Question 1

### Import dataset
- Import iris dataset
- Import the dataset using sklearn library

In [85]:
from sklearn import datasets
iris = datasets.load_iris()

## Question 2

In [22]:
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

### Get features and label from the dataset in separate variable
- you can get the features using .data method
- you can get the features using .target method

In [86]:
X = iris.data
y = iris.target

In [87]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [88]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## Question 3

### Create train and test data
- use train_test_split to get train and test set
- set a random_state
- test_size: 0.25

In [89]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.25,random_state = 42)

In [90]:
X_train[0:3,:]

array([[6.8, 3.2, 5.9, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [5.7, 2.8, 4.1, 1.3]])

## Question 4

### One-hot encode the labels
- convert class vectors (integers) to binary class matrix
- convert labels
- number of classes: 3
- we are doing this to use categorical_crossentropy as loss

In [91]:
# Convert class vectors or integers to binary class matrix
y_train = tf.keras.utils.to_categorical(y_train, num_classes=3)
y_test = tf.keras.utils.to_categorical(y_test, num_classes=3)
## since tensor flow is already intilaized in step 2, else following code : 
### from tensorflow.keras.utils import to_categorical
#### y_train = to_categorical(y_train, num_classes=3)
##### y_test = to_categorical(y_test, num_classes=3)

In [92]:
y_train[0:3]
# target values converted to 0 - 001 , 1 - 010 and 2 as 100

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.]], dtype=float32)

## Question 5

### Initialize a sequential model
- Define a sequential model

In [93]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()

In [68]:
model=tf.keras.Sequential() #or
model.add(tf.keras.layers.Dense(3,activation="softmax",input_shape=(4,)))

## Question 6

### Add a layer
- Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3
- Apply Softmax on Dense Layer outputs

In [94]:
model.add(Dense(3,input_shape=(4,), activation='softmax'))

## Question 7

### Compile the model
- Use SGD as Optimizer
- Use categorical_crossentropy as loss function
- Use accuracy as metrics

In [95]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

## Question 8

### Summarize the model
- Check model layers
- Understand number of trainable parameters

In [96]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


## Question 9

### Fit the model
- Give train data as training features and labels
- Epochs: 100
- Give validation data as testing features and labels

In [97]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=100)

Epoch 1/100
4/4 [==============================] - 1s 75ms/step - loss: 3.0822 - accuracy: 0.2970 - val_loss: 1.3955 - val_accuracy: 0.4474
Epoch 2/100
4/4 [==============================] - 0s 14ms/step - loss: 1.6713 - accuracy: 0.2967 - val_loss: 1.1661 - val_accuracy: 0.1579
Epoch 3/100
4/4 [==============================] - 0s 15ms/step - loss: 1.3372 - accuracy: 0.0692 - val_loss: 1.1453 - val_accuracy: 0.2105
Epoch 4/100
4/4 [==============================] - 0s 14ms/step - loss: 1.2676 - accuracy: 0.2567 - val_loss: 1.1190 - val_accuracy: 0.2632
Epoch 5/100
4/4 [==============================] - 0s 14ms/step - loss: 1.2207 - accuracy: 0.2734 - val_loss: 1.0914 - val_accuracy: 0.1842
Epoch 6/100
4/4 [==============================] - 0s 13ms/step - loss: 1.1635 - accuracy: 0.3122 - val_loss: 1.0587 - val_accuracy: 0.1842
Epoch 7/100
4/4 [==============================] - 0s 13ms/step - loss: 1.1245 - accuracy: 0.2686 - val_loss: 1.0371 - val_accuracy: 0.3158
Epoch 8/100
4/4 [===

## Question 10

### Make predictions
- Predict labels on one row

In [98]:
model.predict([[6.8, 3.2, 5.9, 2.1]])

array([[0.01139732, 0.30202264, 0.68658006]], dtype=float32)

In [ ]:
# Highest probability is class 3, which means the 4 input values are predicted class 3 with accuracy of 68%

### Compare the prediction with actual label
- Print the same row as done in the previous step but of actual labels

In [99]:
y_train[0,:]

array([0., 0., 1.], dtype=float32)



---



# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

### Specifying the TensorFlow version
Running `import tensorflow` will import the default version (currently 1.x). You can use 2.x by running a cell with the `tensorflow_version` magic **before** you run `import tensorflow`.

In [102]:
%tensorflow_version 2.x

### Import TensorFlow
Once you have specified a version via this magic, you can run `import tensorflow` as normal and verify which version was imported as follows:

In [103]:
import tensorflow as tf
print(tf.__version__)

2.4.0


### Set random seed

In [104]:
tf.random.set_seed(42)

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [ ]:
# run this cell to upload file if you are using google colab
from google.colab import files
files.upload()

#time consuming porcess to load to virtual machine, hence skipped

In [125]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [181]:
project_path = '/content/drive/My Drive/Colab Notebooks/'
import pandas as pd
df = pd.read_csv(project_path +'prices.csv')

In [182]:
df.head(15)

date symbol        open  ...         low        high     volume
0   2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1   2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2   2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3   2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4   2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0
5   2016-01-12 00:00:00   WLTW  115.510002  ...  114.500000  116.059998  1098000.0
6   2016-01-13 00:00:00   WLTW  116.459999  ...  112.589996  117.070000   949600.0
7   2016-01-14 00:00:00   WLTW  113.510002  ...  110.050003  115.029999   785300.0
8   2016-01-15 00:00:00   WLTW  113.330002  ...  111.919998  114.879997  1093700.0
9   2016-01-19 00:00:00   WLTW  113.660004  ...  109.870003  115.870003  1523500.0
10  2016-01-20 00:00:00   WLTW  109.059998  ...  108.320000  111.599998  1653900.0
11  2016-01-21 00:00:00   WLTW  109.730003  ...  108.320000  110.580002   944300.0
12  2016-01-22 00:00:00   WLTW  111.879997  ...  110.190002  112.949997   744900.0
13  2016-01-25 00:00:00   WLTW  111.320000  ...  110.000000  114.629997   703800.0
14  2016-01-26 00:00:00   WLTW  110.419998  ...  107.300003  111.400002   563100.0

[15 rows x 7 columns]

In [183]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   date    851264 non-null  object 
 1   symbol  851264 non-null  object 
 2   open    851264 non-null  float64
 3   close   851264 non-null  float64
 4   low     851264 non-null  float64
 5   high    851264 non-null  float64
 6   volume  851264 non-null  float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB


In [184]:
df.shape

(851264, 7)

## Question 2

### Drop columnns
- drop "date" and "symbol" column from the data

In [185]:
prices_new = df.drop(["date", "symbol"],axis=1)

## Question 3

### Take initial rows
- Take first 1000 rows from the data
- This step is done to make the execution faster

In [186]:
prices_new = prices_new.sample(1000,random_state=10)
prices_new.shape

(1000, 5)

## Question 4

In [187]:
prices_new.head

<bound method NDFrame.head of               open       close         low        high      volume
478962   88.660004   89.410004   88.660004   89.639999   3880200.0
601815   35.240002   33.930000   33.680000   35.240002   7508400.0
701659   32.830002   32.970001   32.810001   33.220001   3381500.0
322077   24.709998   25.019996   24.709998   25.060000  14125500.0
538163  211.949997  214.250000  211.830002  215.350006  10993600.0
...            ...         ...         ...         ...         ...
261967   35.070003   35.299997   34.740008   35.330002   5077900.0
779758  178.320007  181.110001  177.820007  181.190002    838000.0
373916    9.260000    9.330000    9.200000    9.400000  10548200.0
342580   12.410000   12.920000   12.200000   13.000000   7475600.0
446892   39.750000   39.500000   39.169998   39.889999   1379500.0

[1000 rows x 5 columns]>

### Get features and label from the dataset in separate variable
- Take "open", "close", "low", "high" columns as features
- Take "volume" column as label
- Normalize label column by dividing it with 1000000

In [ ]:
#volume is target column , open ,close ,low and high --> feature

In [188]:
X= prices_new.drop('volume',axis =1)
y= prices_new['volume']/1000000

## Question 5

### Convert data
- Convert features and labels to numpy array
- Convert their data type to "float32"
 - ##### Converting to float 32 from float 64 - Why???
   - Ans : 1. exploding gradient problem - this is avoided by changing to float 32, so all int or float 64 to float 32
   - 2. vanishing gradient - saddle points , local minimas help get over the problem, but if nn is very deep , and has lots of layers like 20+ 

In [200]:
import numpy as np
X = np.array(X).astype('float32')
y = np.array(y).astype('float32')


## Question 6

### Normalize data
- Normalize features
- Use tf.math.l2_normalize to normalize features
- You can read more about it here https://www.tensorflow.org/api_docs/python/tf/math/l2_normalize

In [201]:
X=tf.math.l2_normalize(X)
#or
#X= tf.math.l2_normalize(X, axis=None, epsilon=1e-12, name=None)

## Question 7

### Define weight and bias
- Initialize weight and bias with tf.zeros
- tf.zeros is an initializer that generates tensors initialized to 0
- Specify the value for shape

In [202]:
W= tf.zeros(shape=(4,1))
b = tf.zeros(shape=(1))

## Question 8

### Get prediction
- Define a function to get prediction
- Approach: prediction = (X * W) + b; here is X is features

In [203]:
@tf.function
def prediction(features, W,b):
  y_pred=tf.add(tf.matmul(features, W), b)
  return y_pred

### Calculate loss
- Calculate loss using predictions
- Define a function to calculate loss
- We are calculating mean squared error

In [204]:
@tf.function
def loss(y_actual, y_predicted):
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    return avg

## Question 9

### Define a function to train the model
1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [205]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    # Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        t.watch([w,b])
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    # Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    # Update Weights and Bias
    w = w - learning_rate * dw
    b = b - learning_rate * db
    
    return w, b

## Question 10

### Train the model for 100 epochs 
- Observe the training loss at every iteration

In [207]:
for i in range(100):    
    W, b = train(X, y, W, b)
    print('Current Training Loss on iteration', i, loss(y, prediction(X, W, b)).numpy())

Current Training Loss on iteration 0 106.42545
Current Training Loss on iteration 1 105.54534
Current Training Loss on iteration 2 104.70011
Current Training Loss on iteration 3 103.88837
Current Training Loss on iteration 4 103.10879
Current Training Loss on iteration 5 102.360115
Current Training Loss on iteration 6 101.64107
Current Training Loss on iteration 7 100.95053
Current Training Loss on iteration 8 100.28734
Current Training Loss on iteration 9 99.65041
Current Training Loss on iteration 10 99.03874
Current Training Loss on iteration 11 98.4513
Current Training Loss on iteration 12 97.88716
Current Training Loss on iteration 13 97.34533
Current Training Loss on iteration 14 96.824974
Current Training Loss on iteration 15 96.32523
Current Training Loss on iteration 16 95.84531
Current Training Loss on iteration 17 95.384384
Current Training Loss on iteration 18 94.94173
Current Training Loss on iteration 19 94.516624
Current Training Loss on iteration 20 94.10834
Current Tra

### Observe values of Weight
- Print the updated values

In [208]:
W

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.05243566],
       [0.05242828],
       [0.05190206],
       [0.05294951]], dtype=float32)>

### Observe values of Bias
- Print the updated values

In [209]:
b.numpy()

array([4.681333], dtype=float32)